variable_name:
  min_length:
    warning: 0
    error: 0
disabled_rules:
  - trailing_newline
  - trailing_whitespace
  - type_name
  - function_parameter_count
  - nesting
  - file_length
  - function_body_length
  - type_body_length
  - line_length
  - cyclomatic_complexity
  - identifier_name
  - multiple_closures_with_trailing_closure
  - valid_ibinspectable
excluded:
  - Pods
  - WeatherInterview/Assets/Generated/R.generated.swift
  - WeatherInterview/Model/ForecastProvider/Models/